"""phase5_order_templates

Revision ID: 0522ef86f205
Revises: aefb61d578c2
Create Date: 2026-08-11 09:33:34.971568
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '0522ef86f205'
down_revision: Union[str, None] = 'aefb61d578c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_templates')
    # ### end Alembic commands ###
