"""production_templates

Revision ID: 0a98e9b441d3
Revises: 83caa0a34a71
Create Date: 2026-08-10 08:20:06.294980
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '0a98e9b441d3'
down_revision: Union[str, None] = '83caa0a34a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('required', sa.Integer(), server_default='500', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_templates')
    # ### end Alembic commands ###
