"""phase3_fields_category_level

Revision ID: 0d4e1c7a2d9a
Revises: 3d2f43826164
Create Date: 2026-08-11 09:48:45.190047
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '0d4e1c7a2d9a'
down_revision: Union[str, None] = '3d2f43826164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('min_level', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('min_level')
        batch_op.drop_column('plant_category')

    # ### end Alembic commands ###
