"""phase0_cards_plots_photos

Revision ID: 131329ec9255
Revises: cd2a3292efa3
Create Date: 2026-08-11 08:34:25.487198
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '131329ec9255'
down_revision: Union[str, None] = 'cd2a3292efa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('crystal_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('is_treasure', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color', 'value', 'is_treasure', name='uq_crystalcard_color_value_treasure')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stitch_condition', sa.Text(), nullable=True))

    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawn_cards_json', sa.Text(), nullable=True))

    with op.batch_alter_table('stitch_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_after_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('photo_before_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('context_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('context_id', sa.Integer(), nullable=True))

    op.execute("UPDATE stitch_reports SET photo_after_url = photo_url")

    with op.batch_alter_table('stitch_reports', schema=None) as batch_op:
        batch_op.alter_column('photo_after_url', nullable=False)
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('tents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawn_cards_json', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tents', schema=None) as batch_op:
        batch_op.drop_column('drawn_cards_json')

    with op.batch_alter_table('stitch_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('context_id')
        batch_op.drop_column('context_type')
        batch_op.drop_column('photo_after_url')
        batch_op.drop_column('photo_before_url')

    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.drop_column('drawn_cards_json')

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('stitch_condition')

    op.drop_table('crystal_cards')
    # ### end Alembic commands ###
