"""plant_beds_and_pet_zones

Revision ID: 25c26a64f99b
Revises: c4cdaba394c1
Create Date: 2026-08-11 19:46:13.940298
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '25c26a64f99b'
down_revision: Union[str, None] = 'c4cdaba394c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('col1', sa.Integer(), nullable=False),
    sa.Column('row1', sa.Integer(), nullable=False),
    sa.Column('col2', sa.Integer(), nullable=False),
    sa.Column('row2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_beds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('col1', sa.Integer(), nullable=False),
    sa.Column('row1', sa.Integer(), nullable=False),
    sa.Column('col2', sa.Integer(), nullable=False),
    sa.Column('row2', sa.Integer(), nullable=False),
    sa.Column('plant_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_beds')
    op.drop_table('pet_zones')
    # ### end Alembic commands ###
