"""phase4_barnyard

Revision ID: 3d2f43826164
Revises: 0522ef86f205
Create Date: 2026-08-11 09:39:25.049467
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '3d2f43826164'
down_revision: Union[str, None] = '0522ef86f205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('barnyard_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='empty', nullable=False),
    sa.Column('accumulated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('required', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_die', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_empty_pen_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_pen_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('image_pen_url')
        batch_op.drop_column('image_empty_pen_url')

    op.drop_table('barnyard_slots')
    op.drop_table('game_media')
    # ### end Alembic commands ###
