"""potion_recipe_description

Revision ID: 70c66a045f31
Revises: 3769d80c0893
Create Date: 2026-08-15 21:33:16.597528
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '70c66a045f31'
down_revision: Union[str, None] = '3769d80c0893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('potion_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potion_recipes', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'plant_beds', ['plant_bed_id'], ['id'])

    with op.batch_alter_table('plant_beds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'plants', ['plant_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['occupant_user_id'], ['vk_id'])

    # ### end Alembic commands ###
