"""unique_product_plant_recipe

Revision ID: 76b459489cd5
Revises: c155fc7cea8f
Create Date: 2026-08-11 17:15:59.596171
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '76b459489cd5'
down_revision: Union[str, None] = 'c155fc7cea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_plant', ['plant_id'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_recipe_plant', ['plant_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_recipe_plant', type_='unique')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_plant', type_='unique')

    # ### end Alembic commands ###
