"""remove_variant_add_unlock_type_image

Revision ID: 7d1614014ed8
Revises: 25c26a64f99b
Create Date: 2026-08-11 20:27:40.417532
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '7d1614014ed8'
down_revision: Union[str, None] = '25c26a64f99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level_gates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlock_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_levelgate_variant_level'), type_='unique')
        batch_op.create_unique_constraint('uq_levelgate_level', ['level'])
        batch_op.drop_column('variant')
        batch_op.drop_column('rewards_json')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('route_variant')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_variant', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('level_gates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rewards_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('variant', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('uq_levelgate_level', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_levelgate_variant_level'), ['variant', 'level'])
        batch_op.drop_column('image_url')
        batch_op.drop_column('unlock_type')

    # ### end Alembic commands ###
