"""orders_user_id_nullable

Revision ID: 83caa0a34a71
Revises: a9aafa369421
Create Date: 2026-08-10 08:00:33.150909
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '83caa0a34a71'
down_revision: Union[str, None] = 'a9aafa369421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
