"""phase6_user_pets

Revision ID: 90a9d7fbb1ae
Revises: 0d4e1c7a2d9a
Create Date: 2026-08-11 10:05:14.445566
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = '90a9d7fbb1ae'
down_revision: Union[str, None] = '0d4e1c7a2d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pet_id', name='uq_userpet_user_pet')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pets')
    # ### end Alembic commands ###
