"""add_name_and_image_url_to_orders

Revision ID: a9aafa369421
Revises: 0007_drop_legacy_bed_cells
Create Date: 2026-08-10 07:44:36.313718
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'a9aafa369421'
down_revision: Union[str, None] = '0007_drop_legacy_bed_cells'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
