"""add_cards_to_draw_and_surcharge_to_production_templates

Revision ID: ae8bee85a788
Revises: f475bc2f7e16
Create Date: 2026-08-11 13:24:11.900267
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'ae8bee85a788'
down_revision: Union[str, None] = 'f475bc2f7e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cards_to_draw', sa.Integer(), server_default='3', nullable=False))
        batch_op.add_column(sa.Column('surcharge', sa.Integer(), server_default='30', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_templates', schema=None) as batch_op:
        batch_op.drop_column('surcharge')
        batch_op.drop_column('cards_to_draw')

    # ### end Alembic commands ###
