"""phase2_levels

Revision ID: aefb61d578c2
Revises: 3e93422cc3de
Create Date: 2026-08-11 09:18:36.982657
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'aefb61d578c2'
down_revision: Union[str, None] = '3e93422cc3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_gates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('coins_required', sa.Integer(), server_default='0', nullable=False),
    sa.Column('plots_required', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rewards_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant', 'level', name='uq_levelgate_variant_level')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('route_variant', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('route_variant')
        batch_op.drop_column('level')

    op.drop_table('level_gates')
    # ### end Alembic commands ###
