"""phase8_potions

Revision ID: b1869f9f174c
Revises: 90a9d7fbb1ae
Create Date: 2026-08-11 10:14:41.442473
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'b1869f9f174c'
down_revision: Union[str, None] = '90a9d7fbb1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potion_recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('ingredient_slots', sa.Text(), nullable=False),
    sa.Column('bonus_code', sa.String(), nullable=True),
    sa.Column('reward_coins', sa.Integer(), server_default='100', nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cauldrons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(), server_default='tin', nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='4', nullable=False),
    sa.Column('status', sa.String(), server_default='empty', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['potion_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_potions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('potion_recipe_id', sa.Integer(), nullable=False),
    sa.Column('bonus_code', sa.String(), nullable=True),
    sa.Column('activated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['potion_recipe_id'], ['potion_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'potion_recipe_id', name='uq_userpotion_user_recipe')
    )
    op.create_table('cauldron_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cauldron_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cauldron_id'], ['cauldrons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cauldron_id', 'slot_index', name='uq_cauldronslot_cauldron_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cauldron_slots')
    op.drop_table('user_potions')
    op.drop_table('cauldrons')
    op.drop_table('potion_recipes')
    # ### end Alembic commands ###
