"""add_unlock_fields_to_users

Revision ID: bee443355cff
Revises: 7d1614014ed8
Create Date: 2026-08-11 20:37:29.457386
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'bee443355cff'
down_revision: Union[str, None] = '7d1614014ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked_barnyard', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('unlocked_pets', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('unlocked_plot_level', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('unlocked_garden_level', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('unlocked_garden_level')
        batch_op.drop_column('unlocked_plot_level')
        batch_op.drop_column('unlocked_pets')
        batch_op.drop_column('unlocked_barnyard')

    # ### end Alembic commands ###
