"""add_image_url_to_products_and_production_templates

Revision ID: c155fc7cea8f
Revises: ae8bee85a788
Create Date: 2026-08-11 13:46:32.706480
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'c155fc7cea8f'
down_revision: Union[str, None] = 'ae8bee85a788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('production_templates', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
