"""plot_norm_revealed

Revision ID: c4cdaba394c1
Revises: 76b459489cd5
Create Date: 2026-08-11 18:12:41.721264
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'c4cdaba394c1'
down_revision: Union[str, None] = '76b459489cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('norm_revealed', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.drop_column('norm_revealed')

    # ### end Alembic commands ###
