"""crystal_norm_images

Revision ID: cd2a3292efa3
Revises: ec117d759fc0
Create Date: 2026-08-10 21:46:02.945449
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'cd2a3292efa3'
down_revision: Union[str, None] = 'ec117d759fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crystal_norm_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color', 'count', name='uq_crystalnormimage_color_count')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crystal_norm_images')
    # ### end Alembic commands ###
