"""add_bonus_kind_to_pets

Revision ID: f475bc2f7e16
Revises: 590dbdfa280b
Create Date: 2026-08-11 12:47:18.555787
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'f475bc2f7e16'
down_revision: Union[str, None] = '590dbdfa280b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_kind', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('bonus_kind')

    # ### end Alembic commands ###
